@echo off
setlocal
cd /d "C:\Users\NyGsoft\Desktop\bot ordenes m"
set "LIVE_LOG_PATH=%CD%\login_medico_live.log"
if not defined PATIENT_KEYS_FILE set "PATIENT_KEYS_FILE=%CD%\patient_keys.txt"
if not defined APPOINTMENT_MEMORY_ENABLED set "APPOINTMENT_MEMORY_ENABLED=1"
if not defined APPOINTMENT_MEMORY_FILE set "APPOINTMENT_MEMORY_FILE=%CD%\appointment_memory_tmp.json"
if not defined APPOINTMENT_MEMORY_TTL_HOURS set "APPOINTMENT_MEMORY_TTL_HOURS=72"
if not defined PRIORITIZE_RECENT_KEYS set "PRIORITIZE_RECENT_KEYS=0"
if not defined KEY_SELECTION_MODE set "KEY_SELECTION_MODE=random"
if not defined KEY_RANDOM_SEED set "KEY_RANDOM_SEED="
if not defined COOP_MODE set "COOP_MODE=1"
if not defined AUTO_CREATE_APPOINTMENT set "AUTO_CREATE_APPOINTMENT=1"
if not defined AUTO_SAVE_APPOINTMENT set "AUTO_SAVE_APPOINTMENT=1"
if not defined AUTO_OPEN_MODULE_AFTER_SAVE set "AUTO_OPEN_MODULE_AFTER_SAVE=1"
if not defined POST_SAVE_REQUIRE_ASSIGNED_MODAL set "POST_SAVE_REQUIRE_ASSIGNED_MODAL=1"
if not defined POST_SAVE_ALLOW_GENERIC_MODULO_FALLBACK set "POST_SAVE_ALLOW_GENERIC_MODULO_FALLBACK=0"
if not defined POST_SAVE_MAX_RETRIES set "POST_SAVE_MAX_RETRIES=4"
if not defined POST_SAVE_RETRY_INTERVAL_MS set "POST_SAVE_RETRY_INTERVAL_MS=90"
if not defined CLICK_SEARCH_AFTER_KEY set "CLICK_SEARCH_AFTER_KEY=0"
if not defined ENABLE_ENTER_FALLBACK set "ENABLE_ENTER_FALLBACK=0"
if not defined STRICT_NUEVA_CITA_MODAL set "STRICT_NUEVA_CITA_MODAL=1"
if not defined CATALOG_LOOP_MAX set "CATALOG_LOOP_MAX=2"
if not defined MAX_KEY_ATTEMPTS set "MAX_KEY_ATTEMPTS=0"
if not defined KEY_SETTLE_MS set "KEY_SETTLE_MS=900"
if not defined KEY_RESOLUTION_TIMEOUT_MS set "KEY_RESOLUTION_TIMEOUT_MS=4200"
if not defined COMMENT_CLICK_RETRIES set "COMMENT_CLICK_RETRIES=3"
if not defined REQUIRE_SAVE_ALERT set "REQUIRE_SAVE_ALERT=1"
if not defined MODULE_LOAD_POLL_TIMEOUT_MS set "MODULE_LOAD_POLL_TIMEOUT_MS=45000"
if not defined MODULE_LOAD_POLL_INTERVAL_MS set "MODULE_LOAD_POLL_INTERVAL_MS=350"
if not defined AUTO_OPEN_NOTA_MEDICA_AFTER_MODULE set "AUTO_OPEN_NOTA_MEDICA_AFTER_MODULE=1"
if not defined NOTA_MEDICA_DELAY_MS set "NOTA_MEDICA_DELAY_MS=2000"
if not defined NOTA_MEDICA_CLICK_TIMEOUT_MS set "NOTA_MEDICA_CLICK_TIMEOUT_MS=12000"
if not defined AUTO_GENERAR_PLAN_TRATAMIENTO set "AUTO_GENERAR_PLAN_TRATAMIENTO=1"
if not defined PLAN_TRATAMIENTO_GENERAR_TIMEOUT_MS set "PLAN_TRATAMIENTO_GENERAR_TIMEOUT_MS=12000"
if not defined REVIEW_HOLD_MS set "REVIEW_HOLD_MS=1800000"
if not defined ERROR_REVIEW_HOLD_MS set "ERROR_REVIEW_HOLD_MS=1800000"
if not defined KEY_EXHAUST_REVIEW_HOLD_MS set "KEY_EXHAUST_REVIEW_HOLD_MS=0"
if not defined STRICT_PREFERRED_SLOT set "STRICT_PREFERRED_SLOT=0"
if not defined RESTART_FROM_LOGIN_ON_BUG set "RESTART_FROM_LOGIN_ON_BUG=1"
if not defined FULL_FLOW_RETRIES set "FULL_FLOW_RETRIES=1"
if not defined TIMEOUT_SCALE set "TIMEOUT_SCALE=0.86"
if not defined MIN_WAIT_MS set "MIN_WAIT_MS=60"
if not defined SLOW_MO_MS set "SLOW_MO_MS=105"
if not defined CANCEL_MAX_APPOINTMENTS set "CANCEL_MAX_APPOINTMENTS=1"
if not defined CANCEL_ACTION_WAIT_TIMEOUT_MS set "CANCEL_ACTION_WAIT_TIMEOUT_MS=10000"
if not defined CANCEL_ACTION_WAIT_INTERVAL_MS set "CANCEL_ACTION_WAIT_INTERVAL_MS=380"
if not defined MODE2_SLOT_MIN_DAY_OFFSET set "MODE2_SLOT_MIN_DAY_OFFSET=1"
if not defined MODE2_SKIP_SUNDAYS set "MODE2_SKIP_SUNDAYS=1"
if not defined MODE2_MAX_SEARCH_WEEKS set "MODE2_MAX_SEARCH_WEEKS=1"
if not defined MODE2_AUTO_FILTER set "MODE2_AUTO_FILTER=0"
if not defined MODE2_MAX_SLOT_CANDIDATES set "MODE2_MAX_SLOT_CANDIDATES=16"
if not defined MODE2_MAX_SLOT_CANDIDATES_PER_DAY set "MODE2_MAX_SLOT_CANDIDATES_PER_DAY=4"

if not defined BOT_MAIN_MODE (
  echo.
  echo =============================
  echo  Menu Principal del Bot
  echo =============================
  echo  1^) Generar ordenes
  echo  2^) Nota medica + Finalizar cita existente
  set /p BOT_MAIN_MODE="Selecciona opcion [1/2] (default 1): "
)
if "%BOT_MAIN_MODE%"=="" set "BOT_MAIN_MODE=1"
if not "%BOT_MAIN_MODE%"=="1" if not "%BOT_MAIN_MODE%"=="2" set "BOT_MAIN_MODE=1"
echo MODO_SELECCIONADO=%BOT_MAIN_MODE%

echo [0/4] Activando Node con nvm...
nvm use 22.12.0 >nul 2>&1
if errorlevel 1 (
  echo No se pudo ejecutar "nvm use 22.12.0".
  echo Verifica que nvm este instalado y esa version exista.
  pause
  exit /b 2
)

echo [1/4] Verificando Playwright (Node)...
node -e "require('playwright')" 2>nul
if errorlevel 1 (
  echo Instalando playwright para Node...
  npm install playwright
)

echo [2/4] Ejecutando login medico...
echo Log en vivo: "%LIVE_LOG_PATH%"
echo BOT_MAIN_MODE=%BOT_MAIN_MODE%  CANCEL_MAX_APPOINTMENTS=%CANCEL_MAX_APPOINTMENTS%  CANCEL_ACTION_WAIT_TIMEOUT_MS=%CANCEL_ACTION_WAIT_TIMEOUT_MS%  CANCEL_ACTION_WAIT_INTERVAL_MS=%CANCEL_ACTION_WAIT_INTERVAL_MS%  MODE2_AUTO_FILTER=%MODE2_AUTO_FILTER%  MODE2_SLOT_MIN_DAY_OFFSET=%MODE2_SLOT_MIN_DAY_OFFSET%  MODE2_SKIP_SUNDAYS=%MODE2_SKIP_SUNDAYS%  MODE2_MAX_SEARCH_WEEKS=%MODE2_MAX_SEARCH_WEEKS%  MODE2_MAX_SLOT_CANDIDATES=%MODE2_MAX_SLOT_CANDIDATES%  MODE2_MAX_SLOT_CANDIDATES_PER_DAY=%MODE2_MAX_SLOT_CANDIDATES_PER_DAY%  COOP_MODE=%COOP_MODE%  AUTO_CREATE_APPOINTMENT=%AUTO_CREATE_APPOINTMENT%  AUTO_SAVE_APPOINTMENT=%AUTO_SAVE_APPOINTMENT%  AUTO_OPEN_MODULE_AFTER_SAVE=%AUTO_OPEN_MODULE_AFTER_SAVE%  POST_SAVE_REQUIRE_ASSIGNED_MODAL=%POST_SAVE_REQUIRE_ASSIGNED_MODAL%  POST_SAVE_ALLOW_GENERIC_MODULO_FALLBACK=%POST_SAVE_ALLOW_GENERIC_MODULO_FALLBACK%  POST_SAVE_MAX_RETRIES=%POST_SAVE_MAX_RETRIES%  POST_SAVE_RETRY_INTERVAL_MS=%POST_SAVE_RETRY_INTERVAL_MS%  STRICT_NUEVA_CITA_MODAL=%STRICT_NUEVA_CITA_MODAL%  CLICK_SEARCH_AFTER_KEY=%CLICK_SEARCH_AFTER_KEY%  ENABLE_ENTER_FALLBACK=%ENABLE_ENTER_FALLBACK%  CATALOG_LOOP_MAX=%CATALOG_LOOP_MAX%  MAX_KEY_ATTEMPTS=%MAX_KEY_ATTEMPTS%  PRIORITIZE_RECENT_KEYS=%PRIORITIZE_RECENT_KEYS%  KEY_SELECTION_MODE=%KEY_SELECTION_MODE%  KEY_RANDOM_SEED=%KEY_RANDOM_SEED%  REQUIRE_SAVE_ALERT=%REQUIRE_SAVE_ALERT%  KEY_SETTLE_MS=%KEY_SETTLE_MS%  KEY_RESOLUTION_TIMEOUT_MS=%KEY_RESOLUTION_TIMEOUT_MS%  COMMENT_CLICK_RETRIES=%COMMENT_CLICK_RETRIES%  MODULE_LOAD_POLL_TIMEOUT_MS=%MODULE_LOAD_POLL_TIMEOUT_MS%  MODULE_LOAD_POLL_INTERVAL_MS=%MODULE_LOAD_POLL_INTERVAL_MS%  AUTO_OPEN_NOTA_MEDICA_AFTER_MODULE=%AUTO_OPEN_NOTA_MEDICA_AFTER_MODULE%  NOTA_MEDICA_DELAY_MS=%NOTA_MEDICA_DELAY_MS%  NOTA_MEDICA_CLICK_TIMEOUT_MS=%NOTA_MEDICA_CLICK_TIMEOUT_MS%  AUTO_GENERAR_PLAN_TRATAMIENTO=%AUTO_GENERAR_PLAN_TRATAMIENTO%  PLAN_TRATAMIENTO_GENERAR_TIMEOUT_MS=%PLAN_TRATAMIENTO_GENERAR_TIMEOUT_MS%  REVIEW_HOLD_MS=%REVIEW_HOLD_MS%  ERROR_REVIEW_HOLD_MS=%ERROR_REVIEW_HOLD_MS%  KEY_EXHAUST_REVIEW_HOLD_MS=%KEY_EXHAUST_REVIEW_HOLD_MS%  STRICT_PREFERRED_SLOT=%STRICT_PREFERRED_SLOT%  RESTART_FROM_LOGIN_ON_BUG=%RESTART_FROM_LOGIN_ON_BUG%  FULL_FLOW_RETRIES=%FULL_FLOW_RETRIES%  PATIENT_KEYS_FILE=%PATIENT_KEYS_FILE%  APPOINTMENT_MEMORY_ENABLED=%APPOINTMENT_MEMORY_ENABLED%  APPOINTMENT_MEMORY_FILE=%APPOINTMENT_MEMORY_FILE%  APPOINTMENT_MEMORY_TTL_HOURS=%APPOINTMENT_MEMORY_TTL_HOURS%  TIMEOUT_SCALE=%TIMEOUT_SCALE%  MIN_WAIT_MS=%MIN_WAIT_MS%  SLOW_MO_MS=%SLOW_MO_MS%
node "login_medico_auto.js"
set "RC=%ERRORLEVEL%"

echo [3/4] Codigo de salida: %RC%
if "%RC%"=="0" (
  echo Login completado.
) else (
  echo No se logro login automatico. Revisa login_medico_error.png
)
echo [4/4] Fin.
pause
endlocal

