@echo off
setlocal

cd /d "C:\Users\NyGsoft\Desktop\bot ordenes m\botGenerarCitasMedicasP2H-QA"

set "BOT_MAIN_MODE=2"
set "CANCEL_MAX_APPOINTMENTS=1"
set "REVIEW_HOLD_MS=30000"
set "ERROR_REVIEW_HOLD_MS=30000"
set "KEY_EXHAUST_REVIEW_HOLD_MS=0"
set "COOP_MODE=1"
set "AUTO_CREATE_APPOINTMENT=1"
set "AUTO_SAVE_APPOINTMENT=1"
set "AUTO_OPEN_MODULE_AFTER_SAVE=1"
set "POST_SAVE_REQUIRE_ASSIGNED_MODAL=1"
set "POST_SAVE_ALLOW_GENERIC_MODULO_FALLBACK=0"
set "POST_SAVE_MAX_RETRIES=4"
set "POST_SAVE_RETRY_INTERVAL_MS=90"
set "CLICK_SEARCH_AFTER_KEY=0"
set "ENABLE_ENTER_FALLBACK=0"
set "STRICT_NUEVA_CITA_MODAL=1"
set "CATALOG_LOOP_MAX=2"
set "MAX_KEY_ATTEMPTS=0"
set "KEY_SETTLE_MS=900"
set "KEY_RESOLUTION_TIMEOUT_MS=4200"
set "COMMENT_CLICK_RETRIES=3"
set "REQUIRE_SAVE_ALERT=1"
set "MODULE_LOAD_POLL_TIMEOUT_MS=90000"
set "MODULE_LOAD_POLL_INTERVAL_MS=350"
set "AUTO_OPEN_NOTA_MEDICA_AFTER_MODULE=1"
set "NOTA_MEDICA_DELAY_MS=2000"
set "NOTA_MEDICA_CLICK_TIMEOUT_MS=12000"
set "AUTO_GENERAR_PLAN_TRATAMIENTO=1"
set "PLAN_TRATAMIENTO_GENERAR_TIMEOUT_MS=12000"
set "STRICT_PREFERRED_SLOT=0"
set "RESTART_FROM_LOGIN_ON_BUG=1"
set "FULL_FLOW_RETRIES=1"
set "PATIENT_KEYS_FILE=%CD%\patient_keys.txt"
set "APPOINTMENT_MEMORY_ENABLED=1"
set "APPOINTMENT_MEMORY_FILE=%CD%\appointment_memory_tmp.json"
set "APPOINTMENT_MEMORY_TTL_HOURS=72"
set "TIMEOUT_SCALE=0.86"
set "MIN_WAIT_MS=60"
set "SLOW_MO_MS=105"
set "PRIORITIZE_RECENT_KEYS=0"
set "KEY_SELECTION_MODE=random"
set "MODE2_SLOT_MIN_DAY_OFFSET=1"
set "MODE2_SKIP_SUNDAYS=1"
set "MODE2_MAX_SEARCH_WEEKS=1"
set "MODE2_AUTO_FILTER=0"
set "MODE2_MAX_SLOT_CANDIDATES=16"
set "MODE2_MAX_SLOT_CANDIDATES_PER_DAY=4"
set "CANCEL_ACTION_WAIT_TIMEOUT_MS=10000"
set "CANCEL_ACTION_WAIT_INTERVAL_MS=380"

echo ========================================
echo  BOT MODE 2 TEST - Popup P2H Fix
echo  BOT_MAIN_MODE=%BOT_MAIN_MODE%
echo ========================================

call nvm use 22.12.0 >nul 2>&1
node login_medico_auto.js
set "RC=%ERRORLEVEL%"
echo.
echo EXIT_CODE=%RC%
pause
endlocal
